print("Please select a character for Beep's eyes:")
eye=input()
print("      \_/")
print("     (" +eye+" "+eye+")")
print("    __)#(__  >>>> BEEP!")
print("   ( )...( )(_)")
print("   || |_| ||//")
print("   () | | ()/")
print("    _(___)_")
print("   [-]   [-]")